### ISSUE TITLE
ubuntu 19.10构建出错

### ISSUE THREAD

**Issue by zhurilinyu** [zlgopen/awtk-lua#2]
scons: done reading SConscript files.
scons: Building targets ...
gcc -o bin/runScript src/run_lua.o src/tk_lua.o -Llib -L/home/awtk/lib -lassets -llua -lassets -lawtk -lextwidgets -lwidgets -lbase -lgpinyin -ltkc -llinebreak -lnanovg -lSDL2 -lglad -lGL -lgtk-3 -lgdk-3 -lXext -lX11 -lsndio -lstdc++ -lpthread -lm -ldl
/usr/bin/ld: lib/liblua.a(loslib.o): in function `os_tmpname':
/home/awtk-lua/3rd/lua/loslib.c:169: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/usr/bin/ld: src/tk_lua.o: in function `to_wstr':
/home/awtk-lua/src/custom.c:164: undefined reference to `utf8_to_utf16'
/usr/bin/ld: src/tk_lua.o: in function `to_str':
/home/awtk-lua/src/custom.c:175: undefined reference to `utf8_from_utf16'
collect2: error: ld returned 1 exit status
scons: *** [bin/runScript] Error 1
scons: building terminated because of errors.

**Comment by xianjimli** [comment]
麻烦更新一下awtk-lua。utf8_to_utf16改名为tk_ utf8_to_utf16了。

**Comment by zhurilinyu** [comment]
可以了
